---
title: "leaflet"
output: html_document
---
```{r, include=FALSE}
library(tidyverse)
library(plotly)
library(flexdashboard)
library(shiny)
library(rsconnect)
library (tigris)
library(rgdal)
library(leaflet)
library(rsconnect)
```

creating polygon map
```{r}
zips = readOGR("./map/nyc_only_zips.shp", layer = "nyc_only_zips")
examplemap = 
leaflet(zips) %>% 
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE)) %>% 
  addProviderTiles(providers$CartoDB.Positron)
```

adding colors
```{r}
leavewkspal <- colorNumeric(
  palette = "viridis",
  domain = as.numeric(zips$leaveweeks), na.color = NA)
wksunpaidpal <- colorNumeric(
  palette = "viridis",
  domain = as.numeric(zips$wksunpaid), na.color = NA)
lvtypepal <- colorFactor(topo.colors(3), zips$leavetype, na.color = NA)
parentpal <- colorFactor(topo.colors(3), zips$parenttype, na.color = NA)
edpal <- colorFactor(topo.colors(3), zips$edtype, na.color = NA)
racepal <- colorFactor(topo.colors(3), zips$race, na.color = NA)
jobtypepal <- colorFactor(topo.colors(3), zips$jobtypefix, na.color = NA)
neighborhoodpal  <- colorFactor(topo.colors(3), zips$X.neighborh, na.color = NA)
```

```{r}
wksunpaid = 
leaflet(zips) %>% 
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~wksunpaidpal(as.numeric(zips$wksunpaid))) %>% 
  addProviderTiles(providers$CartoDB.Positron)
wksunpaid
```

```{r}
leaveweeks = 
leaflet(zips) %>% 
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~leavewkspal(as.numeric(zips$leaveweeks))) %>% 
  addProviderTiles(providers$CartoDB.Positron)
leaveweeks
```

```{r}
leavetype = 
leaflet(zips) %>% 
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~lvtypepal(zips$leavetype)) %>% 
  addProviderTiles(providers$CartoDB.Positron)
leavetype
```

```{r}
parenttype = 
leaflet(zips) %>% 
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~parentpal(zips$parenttype)) %>% 
  addProviderTiles(providers$CartoDB.Positron)
parenttype
```

```{r}
edtype = 
leaflet(zips) %>% 
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~edpal(zips$edtype)) %>% 
  addProviderTiles(providers$CartoDB.Positron)
edtype
```

```{r}
race = 
leaflet(zips) %>% 
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~racepal(zips$race)) %>% 
  addProviderTiles(providers$CartoDB.Positron)
race
```

```{r}
jobtype = 
leaflet(zips) %>% 
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~jobtypepal(zips$jobtypefix)) %>% 
  addProviderTiles(providers$CartoDB.Positron)
jobtype
```

```{r}
neighborhood = 
leaflet(zips) %>% 
    addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~neighborhoodpal(zips$X.neighborh)) %>% 
  addProviderTiles(providers$CartoDB.Positron)
neighborhood
```